# Generated by Django 5.0.6 on 2024-06-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(null=True, upload_to='blog-posts-poster/'),
        ),
    ]
