# Generated by Django 5.0.6 on 2024-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_checkout_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
